# example netlify.toml
[build]
  command = "npm run generate"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "nuxt"
  targetPort = 3000

[functions]
  node_bundler = "esbuild"
